const express = require('express')
const userRoute = require('./user')
const storeRoutes = require('./store')
const routeRoutes = require('./route')
const productRoutes = require('./product')
const manageRoutes = require('./manage')
const cartRoutes = require('./cart')
const orderRoutes = require('./order')
const refundRoutes = require('./refund')
const promotionRoute = require('./promotion')
const distributionRoute = require('./distribution')
const receiveRoute = require('./receive')
const giveRoute = require('./give')
const stockRoute = require('./stock')
const deliveryRoute = require('./delivery')
const sendmoney = require('./sendmoney')
const admin = require('./admin')
const campaign = require('./campaign')
const typetruck = require('./typetrucks')
const { login } = require('../../controllers/authen/login')

const router = express.Router()

router.post('/login', login)
router.use('/user', userRoute)
router.use('/store', storeRoutes)
router.use('/route', routeRoutes)
router.use('/product', productRoutes)
router.use('/manage', manageRoutes)
router.use('/cart', cartRoutes)
router.use('/order', orderRoutes)
router.use('/refund', refundRoutes)
router.use('/promotion', promotionRoute)
router.use('/distribution', distributionRoute)
router.use('/receive', receiveRoute)
router.use('/give', giveRoute)
router.use('/stock', stockRoute)
router.use('/delivery', deliveryRoute)
router.use('/sendmoney', sendmoney)
router.use('/admin', admin)
router.use('/campaign', campaign)
router.use('/typetruck', typetruck)

module.exports = router